apiVersion: v1
kind: Service
metadata:
  name: tensorflow-serving-mnist
spec:
  selector:
    app: tensorflow-serving-mnist
  ports:
  - name: http
    port: 8500
    targetPort: 8500
  type: LoadBalancer