// Jenkinsfile
pipeline {
    agent any

    triggers {
        scm 'H/1 * * * *'
    }

    stages {
        stage('Build') {
            steps {
                sh 'gradle build'
            }
        }
        stage('Test') {
            steps {
                sh 'gradle test'
            }
        }
        stage('Deploy') {
            steps {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh 'aws s3 cp build/libs/helloworld-1.0-SNAPSHOT.jar s3://my-bucket/'
                }
            }
        }
    }
}