global:
  resolve_timeout: 5m

route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default'

receivers:
  - name: 'default'
    email_configs:
      - to: 'your_email@example.com'
        from: 'your_email@example.com'
        smarthost: 'your_smarthost:25'